[[MPItrampoline]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d69736bef7ccbdb453105b342e26b57665db70d7"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8ef1a076fd8096e612dfeb71c4ece8b1b64054c4c736529320caeec831491294"
    url = "https://github.com/giordano/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+3/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran4-cxx11-mpi+mpitrampoline.tar.gz"
